Vagrant.configure("2") do |config|
  config.landrush.enabled = true
  config.vm.provider "virtualbox" do |vb|
	vb.memory = "{{ cfg['memory'] }}"
	vb.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
  end
  config.vm.provider "libvirt" do |vb|
	vb.memory = "{{ cfg['memory'] }}"
  end
  config.vm.define "master1" do |master1|
	master1.vm.box = "{{ vagrant_image }}"
	master1.vm.hostname = "master1.vagrant.test"
	master1.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--memory", "2048"]
	  v.customize ["modifyvm", :id, "--cpus", "1"]
	  v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
	end
  end
  config.vm.define "master2" do |master2|
	master2.vm.box = "{{ vagrant_image }}"
	master2.vm.hostname = "master2.vagrant.test"
	master2.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--memory", "512"]
	  v.customize ["modifyvm", :id, "--cpus", "1"]
	  v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
	end
  end
  config.vm.define "etcd1" do |etcd1|
	etcd1.vm.box = "{{ vagrant_image }}"
	etcd1.vm.hostname = "etcd1.vagrant.test"
	etcd1.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--memory", "512"]
	  v.customize ["modifyvm", :id, "--cpus", "1"]
	  v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
	end
  end
  config.vm.define "etcd2" do |etcd2|
	etcd2.vm.box = "{{ vagrant_image }}"
	etcd2.vm.hostname = "etcd2.vagrant.test"
	etcd2.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--memory", "512"]
	  v.customize ["modifyvm", :id, "--cpus", "1"]
	  v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
	end
  end
  config.vm.define "etcd3" do |etcd3|
	etcd3.vm.box = "{{ vagrant_image }}"
	etcd3.vm.hostname = "etcd3.vagrant.test"
	etcd3.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--memory", "512"]
	  v.customize ["modifyvm", :id, "--cpus", "1"]
	  v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
	end
  end
  config.vm.define "node1" do |node1|
	node1.vm.box = "{{ vagrant_image }}"
	node1.vm.hostname = "node1.vagrant.test"
	node1.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--memory", "512"]
	  v.customize ["modifyvm", :id, "--cpus", "1"]
	  v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
	end
  end
end
