Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "{{ cfg['memory'] }}"
  end
  config.vm.provider "libvirt" do |vb|
    vb.memory = "{{ cfg['memory'] }}"
  end

  (1..3).each do |i|
    config.vm.define "master#{i}" do |master|
      master.vm.box = "{{ vagrant_image }}"
      master.vm.hostname = "master#{i}"
      master.vm.provider :libvirt do |v|
        v.memory = 2048
        v.cpus = 2
      end
      master.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", "1024"]
        v.customize ["modifyvm", :id, "--cpus", "1"]
      end
    end
  end
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "{{ vagrant_image }}"
      node.vm.hostname = "node#{i}"
      node.vm.provider :libvirt do |v|
        v.memory = 1024
        v.cpus = 1
      end
      node.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", "512"]
        v.customize ["modifyvm", :id, "--cpus", "1"]
      end
    end
  end
end
